// <auto-generated />
namespace _18_9_2024.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class lsskl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lsskl));
        
        string IMigrationMetadata.Id
        {
            get { return "202409191047584_lsskl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
