//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _28_7_2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int STUDENTID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string BIRTHDATE { get; set; }
        public string image { get; set; }
    }
}
